FROM golang:1.16-alpine AS build

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
WORKDIR /go/src/vsocksample
COPY . .
RUN go mod download
RUN go build

FROM alpine

WORKDIR /app
COPY --from=build /go/src/vsocksample/vsocksample /app/vsocksample
COPY --from=build /go/src/vsocksample/run.sh /run.sh

CMD [ "/run.sh" ]
