FROM golang:1.16-alpine AS build

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
WORKDIR /go/src/vsocksample
COPY . .
RUN go mod download
RUN go build

FROM scratch

WORKDIR /app
COPY --from=build /go/src/vsocksample/vsocksample /app/vsocksample
CMD [ "/app/vsocksample", "client", "-c", "3", "-p", "5005" ]